import * as fs from "fs";
import * as path from "path";
import archiver from "archiver";
import { workspaceService } from "./workspaceService";
import * as envService from "./envService";

export interface DeployConfig {
  projectId: number;
  name: string;
  type: "static" | "nodejs" | "python" | "docker";
  entryPoint?: string;
  buildCommand?: string;
  startCommand?: string;
  env?: Record<string, string>;
}

export interface DeploymentStatus {
  id: string;
  projectId: number;
  status: "pending" | "building" | "deploying" | "live" | "failed";
  url?: string;
  createdAt: Date;
  error?: string;
}

const deployments = new Map<string, DeploymentStatus>();
const projectDeployConfigs = new Map<number, DeployConfig>();

export async function getDeployConfig(projectId: number): Promise<DeployConfig | null> {
  let config = projectDeployConfigs.get(projectId) || null;
  
  if (!config) {
    config = await detectDeployConfig(projectId);
    if (config) {
      projectDeployConfigs.set(projectId, config);
    }
  }
  
  return config;
}

export async function setDeployConfig(projectId: number, config: Partial<DeployConfig>): Promise<DeployConfig> {
  const existingConfig = await getDeployConfig(projectId);
  const newConfig: DeployConfig = {
    projectId,
    name: config.name || existingConfig?.name || `project-${projectId}`,
    type: config.type || existingConfig?.type || "nodejs",
    entryPoint: config.entryPoint || existingConfig?.entryPoint,
    buildCommand: config.buildCommand || existingConfig?.buildCommand,
    startCommand: config.startCommand || existingConfig?.startCommand,
    env: { ...existingConfig?.env, ...config.env },
  };
  
  projectDeployConfigs.set(projectId, newConfig);
  return newConfig;
}

async function detectDeployConfig(projectId: number): Promise<DeployConfig | null> {
  const workspacePath = workspaceService.getWorkspacePath(projectId);
  
  if (!fs.existsSync(workspacePath)) {
    return null;
  }
  
  const files = fs.readdirSync(workspacePath);
  
  if (files.includes("package.json")) {
    const pkgPath = path.join(workspacePath, "package.json");
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
      
      return {
        projectId,
        name: pkg.name || `project-${projectId}`,
        type: "nodejs",
        entryPoint: pkg.main || "index.js",
        buildCommand: pkg.scripts?.build ? "npm run build" : undefined,
        startCommand: pkg.scripts?.start ? "npm start" : "node index.js",
      };
    } catch {}
  }
  
  if (files.includes("requirements.txt") || files.includes("pyproject.toml")) {
    const mainFile = files.find(f => f === "main.py" || f === "app.py") || "main.py";
    return {
      projectId,
      name: `project-${projectId}`,
      type: "python",
      entryPoint: mainFile,
      startCommand: `python ${mainFile}`,
    };
  }
  
  if (files.includes("index.html")) {
    return {
      projectId,
      name: `project-${projectId}`,
      type: "static",
      entryPoint: "index.html",
    };
  }
  
  if (files.includes("Dockerfile")) {
    return {
      projectId,
      name: `project-${projectId}`,
      type: "docker",
    };
  }
  
  return {
    projectId,
    name: `project-${projectId}`,
    type: "static",
    entryPoint: "index.html",
  };
}

export async function generateDeployPackage(projectId: number): Promise<Buffer> {
  const workspacePath = workspaceService.getWorkspacePath(projectId);
  const config = await getDeployConfig(projectId);
  
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const archive = archiver("zip", { zlib: { level: 9 } });
    
    archive.on("data", (chunk) => chunks.push(chunk));
    archive.on("end", () => resolve(Buffer.concat(chunks)));
    archive.on("error", reject);
    
    archive.directory(workspacePath, false);
    
    if (config) {
      const replitToml = generateReplitToml(config);
      archive.append(replitToml, { name: ".replit" });
      
      const nixConfig = generateNixConfig(config);
      archive.append(nixConfig, { name: "replit.nix" });
    }
    
    archive.finalize();
  });
}

function generateReplitToml(config: DeployConfig): string {
  let content = `# Replit configuration\n`;
  content += `# Generated by BRATVACODER\n\n`;
  
  if (config.type === "nodejs") {
    content += `run = "${config.startCommand || 'npm start'}"\n`;
    content += `entrypoint = "${config.entryPoint || 'index.js'}"\n\n`;
    content += `[languages.nodejs]\n`;
    content += `pattern = "**/*.{js,jsx,ts,tsx}"\n`;
    content += `[languages.nodejs.languageServer]\n`;
    content += `start = "typescript-language-server --stdio"\n\n`;
    content += `[nix]\n`;
    content += `channel = "stable-24_05"\n`;
  } else if (config.type === "python") {
    content += `run = "${config.startCommand || 'python main.py'}"\n`;
    content += `entrypoint = "${config.entryPoint || 'main.py'}"\n\n`;
    content += `[languages.python]\n`;
    content += `pattern = "**/*.py"\n\n`;
    content += `[nix]\n`;
    content += `channel = "stable-24_05"\n`;
  } else if (config.type === "static") {
    content += `run = "python -m http.server 8000"\n`;
    content += `entrypoint = "${config.entryPoint || 'index.html'}"\n\n`;
    content += `[nix]\n`;
    content += `channel = "stable-24_05"\n`;
  }
  
  if (config.env && Object.keys(config.env).length > 0) {
    content += `\n[env]\n`;
    for (const [key, value] of Object.entries(config.env)) {
      content += `${key} = "${value}"\n`;
    }
  }
  
  content += `\n[deployment]\n`;
  content += `deploymentTarget = "cloudrun"\n`;
  content += `build = ["sh", "-c", "${config.buildCommand || ''}"]\n`;
  content += `run = ["sh", "-c", "${config.startCommand || 'npm start'}"]\n`;
  
  return content;
}

function generateNixConfig(config: DeployConfig): string {
  let content = `{ pkgs }: {\n`;
  content += `  deps = [\n`;
  
  if (config.type === "nodejs") {
    content += `    pkgs.nodejs_20\n`;
    content += `    pkgs.nodePackages.typescript-language-server\n`;
  } else if (config.type === "python") {
    content += `    pkgs.python311\n`;
    content += `    pkgs.python311Packages.pip\n`;
  }
  
  content += `  ];\n`;
  content += `}\n`;
  
  return content;
}

export async function createDeployment(projectId: number): Promise<DeploymentStatus> {
  const deployId = `deploy-${projectId}-${Date.now()}`;
  
  const status: DeploymentStatus = {
    id: deployId,
    projectId,
    status: "pending",
    createdAt: new Date(),
  };
  
  deployments.set(deployId, status);
  
  simulateDeployment(deployId);
  
  return status;
}

async function simulateDeployment(deployId: string): Promise<void> {
  const status = deployments.get(deployId);
  if (!status) return;
  
  await new Promise(r => setTimeout(r, 1000));
  status.status = "building";
  
  await new Promise(r => setTimeout(r, 2000));
  status.status = "deploying";
  
  await new Promise(r => setTimeout(r, 1500));
  status.status = "live";
  status.url = `https://project-${status.projectId}.replit.app`;
}

export async function getDeploymentStatus(deployId: string): Promise<DeploymentStatus | null> {
  return deployments.get(deployId) || null;
}

export async function listDeployments(projectId: number): Promise<DeploymentStatus[]> {
  const projectDeployments: DeploymentStatus[] = [];
  
  deployments.forEach((status) => {
    if (status.projectId === projectId) {
      projectDeployments.push(status);
    }
  });
  
  return projectDeployments.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
}

export async function generateReadme(projectId: number): Promise<string> {
  const config = await getDeployConfig(projectId);
  if (!config) {
    return "# Projeto\n\nProjeto gerado pelo BRATVACODER.";
  }
  
  let readme = `# ${config.name}\n\n`;
  readme += `Projeto gerado automaticamente pelo **BRATVACODER**.\n\n`;
  
  readme += `## Tipo de Projeto\n\n`;
  readme += `- **Tipo**: ${config.type}\n`;
  if (config.entryPoint) readme += `- **Entrada**: ${config.entryPoint}\n`;
  readme += `\n`;
  
  readme += `## Como Executar\n\n`;
  
  if (config.type === "nodejs") {
    readme += "```bash\n";
    readme += "npm install\n";
    if (config.buildCommand) readme += `${config.buildCommand}\n`;
    readme += `${config.startCommand || 'npm start'}\n`;
    readme += "```\n\n";
  } else if (config.type === "python") {
    readme += "```bash\n";
    readme += "pip install -r requirements.txt\n";
    readme += `${config.startCommand || 'python main.py'}\n`;
    readme += "```\n\n";
  } else if (config.type === "static") {
    readme += "Abra o arquivo `index.html` no navegador ou use um servidor local:\n\n";
    readme += "```bash\n";
    readme += "python -m http.server 8000\n";
    readme += "```\n\n";
  }
  
  readme += `## Publicacao no Replit\n\n`;
  readme += `1. Importe este projeto no Replit\n`;
  readme += `2. Clique em "Run" para executar\n`;
  readme += `3. Use "Deploy" para publicar\n\n`;
  
  readme += `---\n\n`;
  readme += `Gerado por [BRATVACODER](https://bratvacoder.replit.app)\n`;
  
  return readme;
}
